export const Furniture = [
    {
        id: 1,
        image: '/Furniture.png',
        location: 'Denver, Colorado',
        title: 'Ponte vedra',
        description: 'Nestled in a quiet and picturesque neighborhood, this cozy apartment offers',
        bedrooms: 1,
        workstations: 2,
        bathrooms: 1,
    },
    {
        id: 2,
        image: '/Furniture.png',
        location: 'Denver, Colorado',
        title: 'Ponte vedra',
        description: 'Nestled in a quiet and picturesque neighborhood, this cozy apartment offers',
        bedrooms: 2,
        workstations: 3,
        bathrooms: 2,
    },
    {
        id: 3,
        image: '/Furniture.png',
        location: 'Denver, Colorado',
        title: 'Ponte vedra',
        description: 'Nestled in a quiet and picturesque neighborhood, this cozy apartment offers',
        bedrooms: 3,
        workstations: 4,
        bathrooms: 3,
    },
    {
        id: 4,
        image: '/Furniture.png',
        location: 'Denver, Colorado',
        title: 'Ponte vedra',
        description: 'Nestled in a quiet and picturesque neighborhood, this cozy apartment offers',
        bedrooms: 4,
        workstations: 5,
        bathrooms: 4,
    },
]